---
- name: Ceph Preflight Configuration
  hosts: OSDs
  user: cameron
  sudo: true
  remote_user: root
  tasks:
  - name: Downloading Open SSH
    apt: name=openssh-server state=installed
  - name: Creating ceph users
    shell: sudo useradd -d /home/ceph -m ceph
    ignore_errors: yes
  - name: Setting up password-less sudo (cont'd)
    shell: echo "ceph ALL = (root) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/ceph && sudo chmod 0440 /etc/sudoers.d/ceph

- name: Ceph Deploy setup on Admin node
  hosts: admin
  user: cameron
  sudo: true
  remote_user: root
  tasks:
  - name: Adding key 
    shell: wget -q -O- 'https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc' | sudo apt-key add -
  - name: Updating repositories
    shell: echo deb http://ceph.com/debian-firefly/ $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/ceph.list
  - name: Installing ceph-deploy
    apt: name=ceph-deploy state=installed update_cache=yes

- name: Admin SSH key - Generation
  hosts: admin
  sudo: true
  user: cameron
  remote_user: root
  tasks:
  - name: Generating SSH KEY
    user: name=root generate_ssh_key=yes
  - name: copying the SSH-KEY to the ansible machine
    fetch: src=~/.ssh/id_rsa.pub dest=~/.ssh/tmp/ recursive=yes

- name: Copying admin SSH key to all nodes and updating /etc/hosts file on each machine
  hosts: all 
  user: cameron
  remote_user: cameron
  tasks:
  - name: Copying the SSH-key to the machines
    copy: src=~/.ssh/ dest=~/.ssh/ directory_mode
  - name: removing old authorized_keys
    command: rm ~/.ssh/authorized_keys
  - name: Adding to the list of authorized_keys  
    shell: cat ~/.ssh/tmp/166.78.164.*/root/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - name: Moving inventory to /etc/
    action: copy src=inventory dest=/etc/
  - name: Deleting old hosts file
    command: rm /etc/hosts 
  - name: Renaming inventory to hosts
    command:  mv /etc/inventory /etc/hosts
  - name: Editing /etc/hosts
    command: sed -i '/[admin]/d' /etc/hosts
  - name: Editing /etc/hosts (cont'd)
    command: sed -i '/[OSDs]/d' /etc/hosts
  - name: Editing /etc/hosts (cont'd)
    command: sed -i '/[cephfs]/d' /etc/hosts
