---
- name: Copying admin SSH key to all nodes and updating /etc/hosts file on each machine
  hosts: all 
  user: root
  remote_user: root
  tasks:
  - name: Copying the SSH-key to the machines
    copy: src=~/.ssh/ dest=~/.ssh/ directory_mode
  - name: removing old authorized_keys
    command: rm ~/.ssh/authorized_keys
  - name: Adding to the list of authorized_keys  
    shell: cat ~/.ssh/tmp/166.78.164.*/root/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - name: Moving inventory to /etc/
    action: copy src=inventory dest=/etc/
  - name: Deleting old hosts file
    command: rm /etc/hosts 
  - name: Renaming inventory to hosts
    command:  mv /etc/inventory /etc/hosts
  - name: Editing /etc/hosts
    command: sed -i '/[admin]/d' /etc/hosts
  - name: Editing /etc/hosts (cont'd)
    command: sed -i '/[OSDs]/d' /etc/hosts
  - name: Editing /etc/hosts (cont'd)
    command: sed -i '/[cephfs]/d' /etc/hosts
