---
- name: Creating initial cluster
  hosts: admin
  user: root
  tasks:
  - name: Creating monitor
    shell: ceph-deploy new admin-mon
  - name: Install ceph on OSDs
    shell: ceph-deploy install admin-mon node1 node2 node3
  - name: Add initial monitors
    shell: ceph-deploy mon create-initial
- name: Making directories on OSDs
  hosts: OSDs
  user: ceph-user
  tasks:
  - name: Making a directory on OSDs
    shell: mkdir /var/local/osd
  - name: Preparing OSDs
    shell: ceph-deploy osd prepare node:/var/local/osd
  - name: Activating OSDs
    shell: ceph-deploy activate node:/var/local/osd
  
  
