---
- name: SSH key - Generation
  hosts: admin
  sudo: true
  user: root
  remote_user: root
  tasks:
  - name: Generating SSH KEY
    user: name=root generate_ssh_key=yes
  - name: copying the SSH-KEY to the ansible machine
    fetch: src=~/.ssh/id_rsa.pub dest=~/.ssh/tmp/ recursive=yes
